Homework 01/task 01
jmilic1/code-cadets-2021 pull request #2
Opened 2021-05-11 16:49 UTC by jmilic1

2021-05-12 12:47 UTC, mbekavac-axilis reviewed
Please remove the specification.png as well, it has no place in the code repo.

2021-05-12 12:47 UTC, mbekavac-axilis commented on homework_1/Task-01/main.go
> +	str, err := fizzbuzz.GetFizzBuzz(*start, *end)
`str` is very uninformative, it only hints at the return type which is unnecessary (and, over the long run, harmful)

2021-05-12 12:47 UTC, mbekavac-axilis commented on homework_1/Task-01/main.go
> +	flag.Parse()
what if the `start` and the `end` pointers are nil? this needs to be handled properly

2021-05-12 12:47 UTC, mbekavac-axilis commented on homework_1/Task-01/fizzbuzz/testCases_test.go
> +// Package contains unit tests for FizzBuzz.
we don't usually add comments for the package names as it should be very self-explanatory (and, if it isn't, it's a severe code smell)

2021-05-12 12:47 UTC, mbekavac-axilis commented on homework_1/Task-01/go.sum
> +github.com/gopherjs/gopherjs v0.0.0-20181017120253-0766667cb4d1 h1:EGx4pi6eqNxGaHF6qqu48+N2wcFQ5qg5FXgOdqsJ5d8=
please run `go mod tidy` if you haven't already (everywhere)

2021-05-12 12:47 UTC, mbekavac-axilis commented on homework_1/Task-01/fizzbuzz/fizzBuzz_test.go
> +	for idx, tc := range getTestCases() {
I know abbreviations are quite "idiomatic" in Go, but, in the day of modern IDEs that don't require you to type the entire variable name + no technical restrictions on the length of the variable names as there were 50 years ago - I personally prefer (and encourage/enforce) using more verbose but more informative names - I leave this up to you to decide what to do and how, what you wrote is also ok

2021-05-12 12:47 UTC, mbekavac-axilis commented on homework_1/Task-01/fizzbuzz/fizzBuzz.go
> +	output := ""
much nicer, cleaner and performant way of doing this is adding outputs to a slice for each step and then joining the slice into a string using https://golang.org/pkg/strings/#Join

2021-05-12 12:47 UTC, mbekavac-axilis commented on homework_1/Task-01/fizzbuzz/fizzBuzz.go
> +		if len(str) == 0 {
Using indirect conditions like this is likely to lead to bugs - in case anything else is added above this line, the person must remember to update this line as well. Additionally, it takes several seconds to understand what this is doing (especially since you're using the variable name `str` here, which tells me nothing of what it's used for).

I'd recommend refactoring this into a if-else if-else if-else block for a stricter logic.

2021-05-12 12:57 UTC, mbekavac-axilis commented on homework_1/Task-01/fizzbuzz/testCases_test.go
> +func getTestCases() []testCase {
additionally, some of the use cases are redundant - however, I'm never opposed to having a bit more cases, just in case, unless there's a reason not to include them (e.g. long running time, but then you have a different problem as that means the "units" you're testing are nor small enough)

2021-05-12 13:08 UTC, mbekavac-axilis requested changes
Forgot this isn't my usual team setup where we have some predefined rules for when is the merge allowed (it's not until you get enough approvals) - this means I should be requesting changes rather than just commenting.

2021-05-12 16:47 UTC, jmilic1 commented on homework_1/Task-01/fizzbuzz/fizzBuzz.go
> +		if len(str) == 0 {
I changed the code as you suggested to use if-else blocks, but now ( eg. when i = 4 ) `i % 3  == 0` and `i % 5 == 0`    conditionals are checked twice.

Is it not better to check these conditionals only once?
Is the updated code more favorable because of its readability?

2021-05-12 17:51 UTC, jmilic1 commented on homework_1/Task-01/go.sum
> +github.com/gopherjs/gopherjs v0.0.0-20181017120253-0766667cb4d1 h1:EGx4pi6eqNxGaHF6qqu48+N2wcFQ5qg5FXgOdqsJ5d8=
I tried running it in homework_1/Task-01 folder but nothing changed in `go.sum`. Is there supposed to be less content here?

2021-05-12 18:05 UTC, jmilic1 commented on homework_1/Task-01/main.go
> +	flag.Parse()
In which case would they be `nil` pointers? Doesn't `flag.Int()` return a non-`nil` pointer?

2021-05-13 10:55 UTC, mbekavac-axilis commented on homework_1/Task-01/main.go
> +	flag.Parse()
I don't know, and I don't need to know. The docs are not clear on that point (unless it's buried somewhere in the general section) and there's no guarantee it won't change in the future - they could change the behaviour without breaking the contract - you then update to the latest version of the lib and suddenly you have a new bug. IMO returned pointers should always be checked, no matter how much you trust the third party will "never" return nils (not even by accident).

2021-05-13 10:56 UTC, mbekavac-axilis commented on homework_1/Task-01/go.sum
> +github.com/gopherjs/gopherjs v0.0.0-20181017120253-0766667cb4d1 h1:EGx4pi6eqNxGaHF6qqu48+N2wcFQ5qg5FXgOdqsJ5d8=
It's ok then - it seemed to have a lot of the content, but this might make sense. Also, there are instances when go mod tidy doesn't clean up everything it could, but that's very much out of scope - this is ok.

2021-05-13 11:02 UTC, mbekavac-axilis commented on homework_1/Task-01/fizzbuzz/fizzBuzz.go
> +		if len(str) == 0 {
The way you did it now is, in my opinion, the way to do it.

It's better in terms of readability. It's easier to grasp and it's more compact (I mean it as being harder to accidentally change one thing that completely messes up the logic).

All of that is usually (unless you're doing algorithmic trading or something like that) much more important than saving microseconds with a microoptimisation - there are other things that are inefficient here that account for much bigger impact on the performance, but none of these actually matter, given the context of a FizzBuzz task. Choose your battles carefully, choose well what you optimise.

2021-05-13 11:04 UTC, mbekavac-axilis reviewed
This looks great as-is. If you want, fix that one minor thing before merging.

2021-05-13 11:23 UTC, jmilic1 commented on homework_1/Task-01/fizzbuzz/fizzBuzz.go
> +		if len(str) == 0 {
Understood. Thank you for answering.

2021-05-13 12:13 UTC, mbekavac-axilis approved these changes

2021-05-13 12:30 UTC, merged