Homework 01/task 02
jmilic1/code-cadets-2021 pull request #3
Opened 2021-05-11 16:52 UTC by jmilic1

2021-05-12 13:10 UTC, mbekavac-axilis requested changes
Please fix the general logic before it makes sense for me to review any further.

2021-05-12 13:10 UTC, mbekavac-happening commented on homework_1/Task-02/main.go
> +	AddTaxRange(1000, 0)
Not a nice way to do this - setting a configuration should (from the user's point of view) be atomic whenever possible. Let me know if you need more input on how to solve this.

2021-05-12 13:10 UTC, mbekavac-axilis commented on homework_1/Task-02/main.go
> +	AddTaxRange(1000, 0)
Additionally, it seems like you're changing global variables in the package and using them for calculation. Global = very big no-no, but, paired with non-atomic setup, it just calls for a disaster to happen.

2021-05-12 13:10 UTC, mbekavac-axilis commented on homework_1/Task-02/main.go
> +	AddTaxRange(1000, 0)
Idea to approach this problem - make the function [pure](https://en.wikipedia.org/wiki/Pure_function) - meaning that it always returns the same output no matter what calls you did before. To achieve this, you'll need to provide the `CalculateProgressiveTax` function with both the amount to be taxed as well as the tax brackets. That way you get more flexibility (you can use it for many different tax jurisdictions at the same time) and you don't rely on the setup functions, changing the global state. It also makes it much easier to test.

2021-05-13 11:50 UTC, jmilic1 commented on homework_1/Task-02/main.go
> +	AddTaxRange(1000, 0)
I'll start working on redesigning my solution.

2021-05-13 14:47 UTC, jmilic1 commented on homework_1/Task-02/main.go
> +	AddTaxRange(1000, 0)
@mbekavac-axilis

2021-05-13 17:45 UTC, mbekavac-axilis commented on homework_1/Task-02/calculator/calculator.go
> +	lastThreshold := float32(0)
you don't have to cast it to float, go is smart enough to see it's used as a float later

2021-05-13 17:45 UTC, mbekavac-axilis commented on homework_1/Task-02/calculator/calculator.go
> +	taxRate   float32
it's customary to use float64, unless you have a lot of problems with memory and don't care about precision

2021-05-13 17:45 UTC, mbekavac-axilis commented on homework_1/Task-02/calculator/calculator.go
> +func prepareBracketData(thresholds []float32, taxRates []float32) []taxBracket {
I think it's better to expect the user to create these rather than it being done under the hood - having two slices is no easier for the user than having one slice with structs + you don't have to deal with mismatching number of elements in two slices

2021-05-13 17:45 UTC, mbekavac-axilis commented on homework_1/Task-02/calculator/calculator.go
> +		bracketTaxRate := taxRates[index]
this breaks (panics!) if len(thresholds) > len(taxRates)

2021-05-13 17:45 UTC, mbekavac-axilis commented on homework_1/Task-02/calculator/calculator.go
> +func computeTax(brackets []taxBracket, income float32, finalTaxRate float32) float32 {
the entire function looks quite clean and relatively easy to follow, nice!

2021-05-13 19:37 UTC, jmilic1 commented on homework_1/Task-02/calculator/calculator.go
> +	lastThreshold := float32(0)
Then we have an error saying `Invalid operation: lastThreshold >= threshold (mismatched types int and float32)`

2021-05-13 19:48 UTC, mbekavac-axilis commented on homework_1/Task-02/calculator/calculator.go
> +	lastThreshold := float32(0)
lastThreshold := 0.0

2021-05-13 20:56 UTC, mbekavac-axilis reviewed
These are all minor suggestions - please take them into account, but don't feel obliged to change your code any further. Do it only if you want a sense of closure.

2021-05-13 20:56 UTC, mbekavac-axilis commented on homework_1/Task-02/main.go
> +	taxBrackets := []calculator.TaxBracket{{TaxRate: 0, Threshold: 1000}, {0.1, 5000}, {0.2, 10000}}
noone likes struct oneliners - this can be nicely broken to improve readability

2021-05-13 20:56 UTC, mbekavac-axilis commented on homework_1/Task-02/calculator/calculator.go
> +func CalculateProgressiveTax(taxBrackets []TaxBracket, finalTaxRate float64, income float64) (float64, error) {
I would personally use a bit different logic - define the Threshold as the lower bound, have the first TaxBracket start from Threshold 0 and add the finalTaxRate as the last bracket. What you did is also good, I have nothing against you leaving it as-is, but it might not be as elegant as possible.

2021-05-13 20:56 UTC, mbekavac-axilis commented on homework_1/Task-02/calculator/calculator.go
> +	taxRatesLength := len(taxBrackets)
I would assume taxRatesLength has the length of taxRates, not the length of taxBrackets 😄

2021-05-13 20:56 UTC, mbekavac-axilis commented on homework_1/Task-02/calculator/calculator.go
> +	Threshold float64
IMO this should be called either LowerBound, UpperBound or Lower/UpperThreshold - so that a person using the API doesn't have to guess (or, even worse, read documentation) what the Threshold is

2021-05-14 12:32 UTC, mbekavac-axilis approved these changes

2021-05-29 21:20 UTC, merged